# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setWindowModality(QtCore.Qt.ApplicationModal)
        Login.resize(684, 636)
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setGeometry(QtCore.QRect(390, 10, 291, 611))
        self.frame.setStyleSheet("#frame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-right-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.exitbt = QtWidgets.QPushButton(self.frame)
        self.exitbt.setGeometry(QtCore.QRect(240, 10, 31, 21))
        self.exitbt.setStyleSheet("#exitbt{\n"
"    border:none;\n"
"    \n"
"}\n"
"#exitbt:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.exitbt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitbt.setIcon(icon)
        self.exitbt.setObjectName("exitbt")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 60, 251, 531))
        self.frame_3.setStyleSheet("QLineEdit{\n"
"  \n"
"    background-color: rgba(255, 255, 255,0);\n"
"  border:none;\n"
"  border-bottom:1px solid black;\n"
"}\n"
"QPushButton{\n"
"  \n"
"    background-color: rgb(0, 0, 0);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.userline = QtWidgets.QLineEdit(self.frame_3)
        self.userline.setGeometry(QtCore.QRect(90, 90, 161, 21))
        self.userline.setStyleSheet("QLineEdit{\n"
"  border:none;\n"
"  border-bottom:1px solid black;\n"
"}\n"
"")
        self.userline.setObjectName("userline")
        self.user = QtWidgets.QLabel(self.frame_3)
        self.user.setGeometry(QtCore.QRect(0, 80, 80, 41))
        self.user.setObjectName("user")
        self.pwline = QtWidgets.QLineEdit(self.frame_3)
        self.pwline.setGeometry(QtCore.QRect(90, 190, 161, 21))
        self.pwline.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwline.setObjectName("pwline")
        self.password = QtWidgets.QLabel(self.frame_3)
        self.password.setGeometry(QtCore.QRect(0, 180, 60, 26))
        self.password.setObjectName("password")
        self.identify = QtWidgets.QLabel(self.frame_3)
        self.identify.setGeometry(QtCore.QRect(0, 270, 100, 59))
        self.identify.setObjectName("identify")
        self.idbox = QtWidgets.QComboBox(self.frame_3)
        self.idbox.setGeometry(QtCore.QRect(110, 290, 71, 22))
        self.idbox.setObjectName("idbox")
        self.idbox.addItem("")
        self.idbox.addItem("")
        self.idbox.addItem("")
        self.loginbt = QtWidgets.QPushButton(self.frame_3)
        self.loginbt.setGeometry(QtCore.QRect(70, 390, 150, 40))
        self.loginbt.setObjectName("loginbt")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 20, 128, 31))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(Login)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 381, 641))
        self.frame_2.setStyleSheet("border-image: url(:/images/images/微信图片_1.jpg);\n"
"border-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.retranslateUi(Login)
        self.exitbt.clicked.connect(Login.close)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "图书馆管理系统"))
        self.user.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:12pt;\">用户名</span></p></body></html>"))
        self.password.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:12pt;\">密码</span></p></body></html>"))
        self.identify.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:12pt;\">身份类型</span></p></body></html>"))
        self.idbox.setItemText(0, _translate("Login", "读者"))
        self.idbox.setItemText(1, _translate("Login", "图书管理员"))
        self.idbox.setItemText(2, _translate("Login", "系统管理员"))
        self.loginbt.setText(_translate("Login", "登录"))
        self.label.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:16pt;\">用户登录</span></p></body></html>"))
import resource_rc
